[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  NODE_VERSION = "14.15.0"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'unsafe-inline'; script-src 'unsafe-inline';  script-src-elem 'self'; img-src 'self' data:; connect-src *;"
    Permissions-Policy = "accelerometer=(), autoplay=(), ambient-light-sensor=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), usb=()"
